### ISSUE TITLE
Non-blocking HTTP Requests

### ISSUE THREAD

**Issue by bencz** [coronabytes/dotnet-arangodb#60]
Hi!
It's possible to implement the non-blocking HTTP Requests ?
It's just necessary to send the 'x-arango-async: true' on header... and, also, check the http response status code...

https://www.arangodb.com/docs/stable/http/general.html#blocking-vs-non-blocking-http-requests

**Comment by coronabytes** [comment]
What do you expect to gain from this?
"For clients that are single-threaded or not event-driven, waiting for the full server response may be non-optimal."
Core.ArangoDB is fully async (event-driven) so this is just not needed.

**Comment by bencz** [comment]
Taking my case as an example, I receive approximately 2~5k requests for geolocation updates per second, and this is an update that does not require me to wait for the database to confirm the update... so for a case like this, the async flow, in which I only receive confirmation from the db that the information will be updated, is perfect

I also did a test, I implemented a method in your lib, which makes this async call, and I had a very good performance improvement...

**Comment by coronabytes** [comment]
Now that makes more sense, you want to optimize write-only workload, just like the FireAndForget Mode in Redis.
Well we could do that for Document.Create / Update / Replace with an extra parameter.

However, I still think this is a bad idea because,
the async fifo queue size per default is 4096 and since we're not fetching the results this will never be cleaned up.

and with 5k requests / second there is a possibility to loose msgs (you could raise the queue size of course)

if consistency isn' that important wouldn't it make more sense to just do queue/batch updates yourself (see serilog periodic batching sink)
