### ISSUE TITLE
Handling database restart in app

### ISSUE THREAD

**Issue by killerwife** [coronabytes/dotnet-arangodb#75]
Hello,

I am dealing with a disaster recovery scenario planning. When my app with this driver is running, and the database pod/server restarts, the connection starts failing on:

'{"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}'

What is the suggested recovery scenario in this case that would be in line with the code design.

The default implementation uses AddSingleton. I am aware this is solvable using AddScoped but that then defeats the purpose of having a reusable object.

**Comment by coronabytes** [comment]
what kind of replication are you using?
active fail over is no longer a thing since arango 3.12
and the cluster mode should handle this automatically.

I began rudimentary work to support multiple server endpoints (and switch on failure), however since for "real" production you ought to use cluster I never finished it.

**Comment by coronabytes** [comment]
ah maybe I misunderstood. are you even using replication?
if not you just have to fix your jwt secret in the settings

**Comment by killerwife** [comment]
Oh its not about the db. I basically mean this usecase:

1. start arangodb
2. start dotnet app
3. turn off arangodb
4. call dotnet endpoint for db query - i get cant reach db - this is fine
5. turn on arangodb
6. call dotnet endpoint for db query - i get the 401 error posted above because jwt is expired and is not renewed because Arangodb is a singleton in dotnet and old token is invalid after arangodb restart

**Comment by coronabytes** [comment]
the jwt should not expire, just because arango restarts, see statment above.
If you cannot provide a static jwt secret, then yeah it needs a PR with either a invalidate-jwt method
or it calls it automatically when auth error occurs

as of now the jwt is only invalidated when the expiration time is near (5min offset if i remember correctly)

**Comment by killerwife** [comment]
Alright, thats a good pointer for me. I am using the normal username + password login method which on restart is invalidated, and this is exactly that, on a 401 a new jwt isnt negotiated.

I will close this issue since my question was answered, I will look into handling the 401 and potentially PRing it, but no promises :D
